name: Build

on:
  push:
    branches: main

jobs:
  build:
    runs-on: ubuntu-latest
    container: texlive/texlive:latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Compile
      shell: bash
      run: ./compile.sh
